# Generated by Django 3.1.2 on 2020-10-10 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('optimal_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField(null=True)),
                ('name_de', models.TextField(null=True)),
                ('markdown_description', models.TextField(help_text='The markdown-formatted description')),
                ('markdown_description_en', models.TextField(help_text='The markdown-formatted description', null=True)),
                ('markdown_description_de', models.TextField(help_text='The markdown-formatted description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField(null=True)),
                ('name_de', models.TextField(null=True)),
                ('markdown_description', models.TextField(help_text='The markdown-formatted description')),
                ('markdown_description_en', models.TextField(help_text='The markdown-formatted description', null=True)),
                ('markdown_description_de', models.TextField(help_text='The markdown-formatted description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField(null=True)),
                ('name_de', models.TextField(null=True)),
                ('markdown_description', models.TextField(help_text='The markdown-formatted description')),
                ('markdown_description_en', models.TextField(help_text='The markdown-formatted description', null=True)),
                ('markdown_description_de', models.TextField(help_text='The markdown-formatted description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField()),
                ('count', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.materialcolor')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.materialtype')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materialtype',
            name='production_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.productionmethod'),
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.PositiveIntegerField(help_text='The internal label to identify the material', unique=True)),
                ('consumed', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.materialcolor'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_plastic_tickets.materialtype'),
        ),
    ]
